### PR TITLE
Swift 3 support

### PR DESCRIPTION
**Pull request by onevcat**
I am not sure you like it or not. But there is Swift 3 support for WKZombie.

### CODE REVIEW

**Comment by mkoehnke** [comment]
Hi @onevcat Thanks so much for your contribution. As I didn't have much time to work on WKZombie lately, your pull request is really appreciated. 

**My Plan:** As soon as time permits, I'll probably create a separate swift3 branch with your changes (for review and getting the tests running again). After that, I'll merge everything into master and release a new version (just in time for the Xcode8 release next week).

Thanks!

**Comment by onevcat** [comment]
Sure, that's cool.
And for the test, I guess we can fix it by specifying a aimulator in the test script. It is just because of using a general device now, since the tests are passing locally, so I think it should not be a big issue. (I will have a look at it later if I have more time later)

BTW, great framework. Thank you!

**Comment by mkoehnke** [comment]
Thanks! Yes, that did the trick. I also had to migrate the OSX target and the example project. Take a look at the branch [swift3](https://github.com/mkoehnke/WKZombie/tree/swift3). I'll document the syntax changes and we're done.

**Comment by onevcat** [comment]
👍

**Comment by mkoehnke** [comment]
Closing this PR in favor of #37 that includes migration of OSX target + example project. Thank you.

**Pull request closed without merging**
